FROM python:3-alpine

WORKDIR /usr/src

# Change TimeZone
RUN apk add --update tzdata
ENV TZ=America/Argentina/Buenos_Aires
# Clean APK cache
RUN rm -rf /var/cache/apk/*

RUN pip install gunicorn

ENV FLASK_APP=run.py

EXPOSE 5000
